### ISSUE TITLE
Block explosion dropping items 

### ISSUE THREAD

**Issue by Snownee** [MaxNeedsSnacks/Interactio#13]
Hello, could you please make output of block explosion recipe accepts item, and that will drop items instead of placing blocks?

**Comment by MaxNeedsSnacks** [comment]
The reason I never did this was because I thought this was possible with loot tables, but I could add this, sure!

**Comment by Snownee** [comment]
I have checked the loot table things but it seems impossible to do that.

**Comment by MaxNeedsSnacks** [comment]
I'm not 100% sure how to go about this right now since I want to try not to break existing recipes and / or meddle too much with the existing syntax, but I'll see what I can do ^^

**Comment by MaxNeedsSnacks** [comment]
Not the *best* implementation, but this ***should*** be added on `new-recipe-types` now.

Feel free to give it a whirl ^^

**Comment by Snownee** [comment]
Hi. I tried the new commit and got NPE. Did I do anything wrong?

```
{
  "type": "interactio:block_explode",
  "input": {
    "block": "brown_concrete"
  },
  "output": {
    "item": "blaze_powder"
  }
}
```

**Comment by MaxNeedsSnacks** [comment]
Hey, could you give me the stacktrace or the full latest.log file? Might've forgotten to take care of some cases

**Comment by Snownee** [comment]
```
[m[1;31m[17:07:36] [Server thread/ERROR] [minecraft/MinecraftServer]: Failed to reload data packs
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:1.8.0_191] {}
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_191] {}
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1467) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_193031_aM(MinecraftServer.java:1440) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.command.impl.ReloadCommand.func_198598_a(SourceFile:16) ~[?:?] {re:classloading}
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[brigadier-1.0.17.jar:?] {re:classloading}
	at net.minecraft.command.Commands.func_197059_a(Commands.java:205) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:990) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:973) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191] {}
Caused by: java.lang.NullPointerException
	at dev.maxneedssnacks.interactio.recipe.ingredient.WeightedOutput.deserialize(WeightedOutput.java:148) ~[?:1.15.2-2.0.2] {re:classloading}
	at dev.maxneedssnacks.interactio.Utils.singleOrWeighted(Utils.java:90) ~[?:1.15.2-2.0.2] {re:classloading}
	at dev.maxneedssnacks.interactio.recipe.BlockExplosionRecipe$Serializer.read(BlockExplosionRecipe.java:87) ~[?:1.15.2-2.0.2] {re:classloading}
	at dev.maxneedssnacks.interactio.recipe.BlockExplosionRecipe$Serializer.func_199425_a_(BlockExplosionRecipe.java:84) ~[?:1.15.2-2.0.2] {re:classloading}
	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:interactio.mixins.json:RecipeManagerMixin,pl:mixin:A}
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:60) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:interactio.mixins.json:RecipeManagerMixin,pl:mixin:A}
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:37) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:interactio.mixins.json:RecipeManagerMixin,pl:mixin:A}
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_191] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_191] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_191] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1464) ~[?:?] {re:classloading,pl:accesstransformer:B}
	... 21 more
```

**Comment by MaxNeedsSnacks** [comment]
Hm, that's odd, it works perfectly fine in my test world...

Keep in mind I haven't released this version of the mod anywhere yet, but if you've compiled it yourself, I ***really*** can't see why this is erroring... hm

**Comment by Snownee** [comment]
Are you using the recipe that I provide?

**Comment by MaxNeedsSnacks** [comment]
Yup, that exact recipe

![image](https://user-images.githubusercontent.com/12750501/84014684-03520580-a97b-11ea-823b-8daa665cf00e.png)

![image](https://user-images.githubusercontent.com/12750501/84014748-1ebd1080-a97b-11ea-9f3c-91e82dc67bd7.png)

**Comment by Snownee** [comment]
I forgot to copy the file. Sorry to bother asking.

**Comment by MaxNeedsSnacks** [comment]
No worries, and thanks for testing again! I might push this update out either today or tomorrow, depending on the amount of free time I have

**Comment by Snownee** [comment]
Thanks for your work. That helps me a lot
