### ISSUE TITLE
Crash when Attempting F->I transform on DedServer

### ISSUE THREAD

**Issue by Nachtflame** [MaxNeedsSnacks/Interactio#4]
So, recipe works great in SinglePlayer, but [does not show in JEI &] causes crash on Dedicated Server with the following crash report

forge 28.2.1
Interactio 1.3.0

```Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.item.ItemEntity.func_70016_h(DDD)V
        at dev.maxneedssnacks.interactio.recipe.ItemFluidTransformRecipe.craft(ItemFluidTransformRecipe.java:103) ~[?:1.15.2-1.3.0] {re:classloa$
        at dev.maxneedssnacks.interactio.event.DroppedItemHandler.lambda$null$1(DroppedItemHandler.java:34) ~[?:1.15.2-1.3.0] {re:classloading}
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_242] {}
        at dev.maxneedssnacks.interactio.recipe.util.InWorldRecipeType.apply(InWorldRecipeType.java:106) ~[?:1.15.2-1.3.0] {re:classloading}
        at dev.maxneedssnacks.interactio.event.DroppedItemHandler.lambda$new$2(DroppedItemHandler.java:33) ~[?:1.15.2-1.3.0] {re:classloading}
        at dev.maxneedssnacks.interactio.event.DroppedItemHandler.lambda$null$9(DroppedItemHandler.java:77) ~[?:1.15.2-1.3.0] {re:classloading}
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_242] {}
        at dev.maxneedssnacks.interactio.event.DroppedItemHandler.lambda$t1ckt0ck$10(DroppedItemHandler.java:77) ~[?:1.15.2-1.3.0] {re:classload$
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_242] {}
        at dev.maxneedssnacks.interactio.event.DroppedItemHandler.t1ckt0ck(DroppedItemHandler.java:64) ~[?:1.15.2-1.3.0] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_178_DroppedItemHandler_t1ckt0ck_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:99) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:835) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtime$
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtime$
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleane$
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}

**Comment by MaxNeedsSnacks** [comment]
Oh dear, that's not good... This is what I get for trying to make everything cross-compatible all the tim e :P 

Let me see what's wrong here

**Comment by MaxNeedsSnacks** [comment]
Oh dear, that's... not good, actually.
It might be doing clientside code on server again... let me see whether I can fix this somehow

**Comment by MaxNeedsSnacks** [comment]
Oh goddamnit yeah it is, let me push a hotfix once I'm done with testing

**Comment by MaxNeedsSnacks** [comment]
These two commits should have (hopefully) fixed both of these issues, I'll have a hotfix up on CurseForge soon ^^

**Comment by Nachtflame** [comment]
Thank you for the speedy responses/fixes! Will test it soon!

**Comment by Nachtflame** [comment]
Success! 
This mod perfectly fits a need I had for my pack.  I am quite appreciative of your work here. :)

**Comment by MaxNeedsSnacks** [comment]
Glad to hear the mod's been helpful to you ^^
I mainly have... a **lot** of free time currently, so updating this mod actually gives me stuff to do at the moment and saves me from being bored, so if you have anything that you feel is missing, feel free to just ask and I'll see what I can do :p
